# Generated by Django 5.2.8 on 2026-03-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readquest", "0002_book_currently_reading_alter_book_cover_image_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="ol_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="blurb",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(default=0),
        ),
    ]
