# Generated by Django 4.2.27 on 2026-03-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0004_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='current_goals',
        ),
    ]
