# Generated by Django 4.2.27 on 2026-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0005_rename_goal_goal_current_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_goals',
        ),
        migrations.AddField(
            model_name='goal',
            name='title_goals',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
