# Generated by Django 4.2.27 on 2026-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0006_remove_goal_current_goals_goal_title_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='books',
            field=models.IntegerField(default=0),
        ),
    ]
