# Generated by Django 4.2.27 on 2026-03-15 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readquest', '0007_goal_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_goals',
            field=models.ManyToManyField(related_name='current_goals', to=settings.AUTH_USER_MODEL),
        ),
    ]
