# Generated by Django 4.2.27 on 2026-03-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0008_goal_current_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='title_goals',
            new_name='title_goal',
        ),
    ]
