# Generated by Django 4.2.27 on 2026-03-15 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0009_rename_title_goals_goal_title_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
