# Generated by Django 4.2.27 on 2026-03-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readquest', '0011_bookread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRead',
        ),
    ]
