# Generated by Django 6.0.3 on 2026-03-16 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("readquest", "0012_delete_bookread"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True, related_name="completed_goals", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
