# Generated by Django 4.2.27 on 2026-03-17 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readquest', '0014_remove_book_date_read_remove_book_read_by_readrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_by',
            field=models.ManyToManyField(related_name='read_by', through='readquest.ReadRecord', to=settings.AUTH_USER_MODEL),
        ),
    ]
